# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marti/Info_perso/apprentissage_C++/projet_labyrinthe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marti/Info_perso/apprentissage_C++/projet_labyrinthe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marti/Info_perso/apprentissage_C++/projet_labyrinthe/CMakeFiles /home/marti/Info_perso/apprentissage_C++/projet_labyrinthe//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marti/Info_perso/apprentissage_C++/projet_labyrinthe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projet_labyrinthe

# Build rule for target.
projet_labyrinthe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projet_labyrinthe
.PHONY : projet_labyrinthe

# fast build rule for target.
projet_labyrinthe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/build
.PHONY : projet_labyrinthe/fast

src/etats_jeu.o: src/etats_jeu.cpp.o
.PHONY : src/etats_jeu.o

# target to build an object file
src/etats_jeu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/etats_jeu.cpp.o
.PHONY : src/etats_jeu.cpp.o

src/etats_jeu.i: src/etats_jeu.cpp.i
.PHONY : src/etats_jeu.i

# target to preprocess a source file
src/etats_jeu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/etats_jeu.cpp.i
.PHONY : src/etats_jeu.cpp.i

src/etats_jeu.s: src/etats_jeu.cpp.s
.PHONY : src/etats_jeu.s

# target to generate assembly for a file
src/etats_jeu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/etats_jeu.cpp.s
.PHONY : src/etats_jeu.cpp.s

src/fonctions_generales.o: src/fonctions_generales.cpp.o
.PHONY : src/fonctions_generales.o

# target to build an object file
src/fonctions_generales.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/fonctions_generales.cpp.o
.PHONY : src/fonctions_generales.cpp.o

src/fonctions_generales.i: src/fonctions_generales.cpp.i
.PHONY : src/fonctions_generales.i

# target to preprocess a source file
src/fonctions_generales.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/fonctions_generales.cpp.i
.PHONY : src/fonctions_generales.cpp.i

src/fonctions_generales.s: src/fonctions_generales.cpp.s
.PHONY : src/fonctions_generales.s

# target to generate assembly for a file
src/fonctions_generales.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/fonctions_generales.cpp.s
.PHONY : src/fonctions_generales.cpp.s

src/labyrinthe.o: src/labyrinthe.cpp.o
.PHONY : src/labyrinthe.o

# target to build an object file
src/labyrinthe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/labyrinthe.cpp.o
.PHONY : src/labyrinthe.cpp.o

src/labyrinthe.i: src/labyrinthe.cpp.i
.PHONY : src/labyrinthe.i

# target to preprocess a source file
src/labyrinthe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/labyrinthe.cpp.i
.PHONY : src/labyrinthe.cpp.i

src/labyrinthe.s: src/labyrinthe.cpp.s
.PHONY : src/labyrinthe.s

# target to generate assembly for a file
src/labyrinthe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/labyrinthe.cpp.s
.PHONY : src/labyrinthe.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_labyrinthe.dir/build.make CMakeFiles/projet_labyrinthe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... projet_labyrinthe"
	@echo "... src/etats_jeu.o"
	@echo "... src/etats_jeu.i"
	@echo "... src/etats_jeu.s"
	@echo "... src/fonctions_generales.o"
	@echo "... src/fonctions_generales.i"
	@echo "... src/fonctions_generales.s"
	@echo "... src/labyrinthe.o"
	@echo "... src/labyrinthe.i"
	@echo "... src/labyrinthe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

